#' Start a BDA procedure for all codons
#' 
#' To generate a BDA based binary representation of a code or a sequence of codons, you need to start a BDA procedure first. 
#' To do so you can eihter call \code{\link{code_start_bda}} or \code{\link{seq_start_bda}}. To start a procedure
#' for all RNA codons call \code{\link{start_bda}}.
#' To add a BDA simply Call \code{\link{add_bda}}. To execute the BDAs call \code{\link{run_bda_as_matrix}} or \code{\link{run_bda}}.
#' A binary dichotomic algorithm generates a binary representation of a generic code. For more info on BDAs read:\cr
#' \emph{M.Gumbel, E.Fimmel, A.Danielli, L.Struengmann. On Models of the Genetic  Code generated by Binary Dichotomic Algorithms}
#' 
#' @return Boolean value. True if the procedure has started
#' @examples
#' start_bda()
#' add_bda(1, 2, "C", "G", "A", "U")
#' add_bda(1, 3, "A", "G", "C", "U")
#' res <- run_bda_as_matrix()
#' 
#' @export 
start_bda <- function() {
  return(code_start_bda(get_rna_codon_list()))
}

#' Execute BDA procedure (only works for all codons).
#' 
#' Run the currently open BDA procedure. Therefore, you need to start a BDA procedure. For this method the procedure has to be started by the \code{\link{start_bda}} function. To start a procedure
#' for all codons call \code{\link{start_bda}}.
#' To add a BDA simply Call \code{\link{add_bda}}. To execute the BDAs call \code{\link{run_bda_as_matrix}} or \code{\link{run_bda}}.
#' A binary dichotomic algorithm generates a binary representation of a generic code. For more info on BDAs read:read:\cr
#' \emph{M.Gumbel, E.Fimmel, A.Danielli, L.Struengmann. On Models of the Genetic  Code generated by Binary Dichotomic Algorithms}
#' 
#' @examples
#' start_bda()
#' add_bda(1, 2, "C", "G", "A", "U")
#' add_bda(1, 3, "A", "G", "C", "U")
#' res <- run_bda_as_matrix()
#' 
#' @export 
run_bda_as_matrix <- function() {
  res <- run_bda()
  error_msg = "run_bda_as_matrix only works for the correct codon table restar bda procedure with start_bda"
  rna_list = get_rna_codon_list()
  if(length(res$code) != length(rna_list)) {
    stop(error_msg ) 
  }
  for(i in 1:length(res$code)) {
    if(rna_list[i] != res$code[i]) {
      stop(error_msg ) 
    }
    
    rna_list[i] = paste(rna_list[i], res$bda[i], sep=" -> ")
  }
  
  return(factor_rna_codon_table(rna_list))
}