# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_bda_rule <- function(i_1, i_2, Q_11, Q_12, Q_21, Q_22) {
    .Call(`_GCATR_add_bda_rule`, i_1, i_2, Q_11, Q_12, Q_21, Q_22)
}

start_bda_for_code <- function(code) {
    .Call(`_GCATR_start_bda_for_code`, code)
}

run_bda <- function() {
    .Call(`_GCATR_run_bda`)
}

check_if_circular <- function(code) {
    .Call(`_GCATR_check_if_circular`, code)
}

check_if_cn_circular <- function(code) {
    .Call(`_GCATR_check_if_cn_circular`, code)
}

check_if_comma_free <- function(code) {
    .Call(`_GCATR_check_if_comma_free`, code)
}

check_if_self_complementary <- function(code) {
    .Call(`_GCATR_check_if_self_complementary`, code)
}

get_acid <- function(code) {
    .Call(`_GCATR_get_acid`, code)
}

get_one_logest_path_as_vector <- function(code) {
    .Call(`_GCATR_get_one_logest_path_as_vector`, code)
}

get_all_logest_path_as_vector <- function(code) {
    .Call(`_GCATR_get_all_logest_path_as_vector`, code)
}

get_one_circle_as_vector <- function(code) {
    .Call(`_GCATR_get_one_circle_as_vector`, code)
}

get_all_circle_as_vector <- function(code) {
    .Call(`_GCATR_get_all_circle_as_vector`, code)
}

